spring:
  application:
    name: hcc-repository
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hcc_repository?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&connectTimeout=2000&socketTimeout=150000
    username: root
    password: 123456

server:
  port: 8089
  servlet:
    context-path: /hcc-repo

logging:
  level:
    com.hcc: debug

hcc:
  repository:
    enableBanner: true
    entityPackages:
      - com.hcc.repository.test.domain.po
#debug: true